stages:
  - lint
  - build

variables:
  PATH_DOCKERFILE: $CI_PROJECT_DIR
  IMAGE_NAME: iorio_apps

lint-dockerfile:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint $PATH_DOCKERFILE/Dockerfile

build-apps-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat $CI_SERVER_TLS_CA_FILE >> /kaniko/ssl/certs/ca-certificates.crt
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $PATH_DOCKERFILE/Dockerfile --destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_TAG --cache=false
  rules:
   - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'

