#!/bin/sh

JSON_STRING='window.configs = { \
  "VITE_URL_IORIO_CCR_BACKEND":"'"${VITE_URL_IORIO_CCR_BACKEND}"'", \
  "VITE_URL_AUTH_SERVER":"'"${VITE_URL_AUTH_SERVER}"'", \
  "VITE_AUTH_REALM":"'"${VITE_AUTH_REALM}"'", \
  "VITE_AUTH_CLIENT_ID" :"'"${VITE_AUTH_CLIENT_ID}"'", \
  "VITE_AUTH_CLIENT_ROLES":"'"${VITE_AUTH_CLIENT_ROLES}"'", \
  "VITE_URL_IORIO_CCR_FILESERVER":"'"${VITE_URL_IORIO_CCR_FILESERVER}"'", \
  "VITE_URL_IORIO_DASHBOARD":"'"${VITE_URL_IORIO_DASHBOARD}"'", \
  "VITE_CONNECTION_TIMEOUT_MS":"'"${VITE_CONNECTION_TIMEOUT_MS}"'", \
  "VITE_ENV":"'"${VITE_ENV}"'", \
}'
sed -i "s@// CONFIGURATIONS_PLACEHOLDER@${JSON_STRING}@" /usr/share/nginx/html/index.html

exec "$@"